/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClienteController;
import Controller.FilmeController;
import Model.TableModelCliente;
import Model.TableModelFilme;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import miscellaneous.Database;
import miscellaneous.FabricaAbstrata;

/**
 *
 * @author Higor Alves
 */
public class FilmeView extends javax.swing.JInternalFrame implements View{
    private static FilmeView instancia = null;
    private TableModelFilme tableModel = new TableModelFilme(Database.getInstancia().getFilmes());
    private FilmeController controller = (FilmeController) FabricaAbstrata.getFabrica("filme").criarControle();
    /**
     * Creates new form FilmeView
     */
    private FilmeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfTitulo1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfFaixaEtaria1 = new javax.swing.JTextField();
        btSalvar1 = new javax.swing.JButton();
        btEditar1 = new javax.swing.JButton();
        btDeletar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFilme = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAbrir = new javax.swing.JMenuItem();
        miSalvar = new javax.swing.JMenuItem();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Titulo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));
        jPanel1.add(tfTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 12, 100, -1));

        jLabel4.setText("Faixa Etaria");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 15, -1, -1));
        jPanel1.add(tfFaixaEtaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 12, 50, -1));

        btSalvar1.setText("Salvar");
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 11, -1, -1));

        btEditar1.setText("Editar");
        btEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 11, -1, -1));

        btDeletar1.setText("Deletar");
        btDeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btDeletar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 11, -1, -1));

        tableFilme.setAutoCreateRowSorter(true);
        tableFilme.setModel(tableModel);
        jScrollPane2.setViewportView(tableFilme);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 464, 283));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 330));

        jMenu1.setText("File");

        miAbrir.setText("Abrir");
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(miAbrir);

        miSalvar.setText("Salvar");
        miSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(miSalvar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        try{
            if(controller.addRow(tfTitulo1.getText(), Integer.parseInt(tfFaixaEtaria1.getText()))){
                tableModel.updateTable();
                tfTitulo1.setText("");
                tfFaixaEtaria1.setText("");
                popUpSucesso(jPanel1, "Filme Cadastrado com sucesso!");
            }else{
                popUpError(jPanel1, "Não foi possivel Cadastrar", "Filme ja existe ou falta preencher algum campo");
            }
        }catch(NumberFormatException e){
            popUpError(jPanel1, "Error", "Faixa Etaria não pode ser letra!");
        }

    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void btEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditar1ActionPerformed
        try{
            if (tableFilme.getSelectedRow() != -1){
                int id = (int)tableModel.getValueAt(tableFilme.getSelectedRow(), 0);
                String titulo = (String) tableModel.getValueAt(tableFilme.getSelectedRow(), 1);
                int faixaEtaria = (int) tableModel.getValueAt(tableFilme.getSelectedRow(), 2);
                String alugado = (String) tableModel.getValueAt(tableFilme.getSelectedRow(), 3);

                if(controller.alterarRow(id, titulo, faixaEtaria, alugado, tfTitulo1.getText(), Integer.parseInt(tfFaixaEtaria1.getText()))){
                    popUpSucesso(jPanel1, "Filme alterado com sucesso.");
                    tfTitulo1.setText("");
                    tfFaixaEtaria1.setText("");
                    tableModel.updateTable();
                }
                
            }
        }catch (NumberFormatException e){
            popUpError(jPanel1, "Error", "Faixa Etaria não pode ser letra!");
            System.out.print(e);
        }
    }//GEN-LAST:event_btEditar1ActionPerformed

    private void btDeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletar1ActionPerformed
        try{
            int id = (int) tableModel.getValueAt(tableFilme.getSelectedRow(), 0);
            if (controller.removerRow(id)){
                tableModel.updateTable();
                popUpSucesso(jPanel1, "Filme deletado com sucesso!");
            }
        }catch (IndexOutOfBoundsException e){
            popUpError(jPanel1, "Não foi possivel deletar", "Verifique se você selecionou algum filme!");
        }
    }//GEN-LAST:event_btDeletar1ActionPerformed

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        try{
            String path = null;
            JFileChooser filechooser = new JFileChooser();
            filechooser.setDialogTitle("Procurar base de dados do Filme");
            filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            FileNameExtensionFilter filter = new FileNameExtensionFilter("csv", "csv");
            filechooser.setFileFilter(filter);
            int retorno = filechooser.showOpenDialog(this);

            if(retorno == JFileChooser.APPROVE_OPTION){
                File file = filechooser.getSelectedFile();
                path = file.getAbsolutePath();
            }
            controller.abrirArq(path);
            tableModel.updateTable();
        }catch(NullPointerException e){
        }
    }//GEN-LAST:event_miAbrirActionPerformed

    private void miSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalvarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Onde você deseja salvar?");   
        FileNameExtensionFilter filter = new FileNameExtensionFilter("csv", "csv");
        fileChooser.setFileFilter(filter);
        int userSelection = fileChooser.showSaveDialog(jPanel1);
 
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            controller.salvarArq(fileToSave.getAbsolutePath());
        }
    }//GEN-LAST:event_miSalvarActionPerformed

    private void popUpSucesso(JPanel pane, String mensagem){
        JOptionPane.showMessageDialog(pane,mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }
    private void popUpError(JPanel pane, String titulo, String mensagem){
        JOptionPane.showMessageDialog(pane, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }
    
    public static FilmeView getInstancia(){
        if (instancia == null){
            instancia = new FilmeView();
        }
        return instancia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeletar1;
    private javax.swing.JButton btEditar1;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miSalvar;
    private javax.swing.JTable tableFilme;
    private javax.swing.JTextField tfFaixaEtaria1;
    private javax.swing.JTextField tfTitulo1;
    // End of variables declaration//GEN-END:variables
}
